package br.inf.carlos.wfg2.gui.panels;

/**
 *
 * @author carlos
 */
public class PainelComponenteSaveConfiguracao extends javax.swing.JPanel {

    /** Creates new form PainelComponenteText */
    public PainelComponenteSaveConfiguracao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	jButton1 = new javax.swing.JButton();

        setBorder(null);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Salvar");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
