package br.inf.carlos.wfg2.gui.panels;

import java.io.IOException;

import br.inf.carlos.wfg2.component.WebComponent;
import br.inf.carlos.wfg2.gui.actions.ButtonCarregaFrameBase;
import br.inf.carlos.wfg2.gui.models.DefaultClassListModel;

/**
 *
 * @author carlos
 */
public class PainelClassSelector extends javax.swing.JPanel {

    /** Creates new form PainelClassSelector */
    public PainelClassSelector() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pacoteBeans = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        classes = new javax.swing.JList();
        button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Pacote das Classes:");

        pacoteBeans.setText("br.inf.carlos.teste.beans");

        try {
			classes.setModel(new DefaultClassListModel(WebComponent.getPackageClasses(pacoteBeans.getText())));
		} catch (IOException e) {
			e.printStackTrace();
		}
        jScrollPane1.setViewportView(classes);

        button.setText("Abrir Gerador");

        jLabel2.setText("Classes do Pacote:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pacoteBeans, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pacoteBeans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        
        this.button.addActionListener(new ButtonCarregaFrameBase(this));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList classes;
    private javax.swing.JButton button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pacoteBeans;
    
    // End of variables declaration//GEN-END:variables
	public javax.swing.JList getClasses() {
		return classes;
	}

	public void setClasses(javax.swing.JList classes) {
		this.classes = classes;
	}

	public javax.swing.JTextField getPacoteBeans() {
		return pacoteBeans;
	}

	public void setPacoteBeans(javax.swing.JTextField pacoteBeans) {
		this.pacoteBeans = pacoteBeans;
	}

    
}
